CREATE TABLE IF NOT EXISTS sign (
    id VARCHAR(50) PRIMARY KEY,
    label VARCHAR(60) NOT NULL,
    description VARCHAR(280),
    is_bimanual BOOLEAN NOT NULL DEFAULT FALSE,
    sample_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sign_sample (
    id VARCHAR(80) PRIMARY KEY,
    sign_id VARCHAR(50) NOT NULL REFERENCES sign (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duration_ms INTEGER NOT NULL,
    frame_count INTEGER NOT NULL,
    frames JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sign_sample_sign_id ON sign_sample (sign_id);
